apiVersion: v1
kind: Pod
metadata:
  name: bunk-login
spec:
  containers:
  - name: ubuntu
    image: bunk-login
    ports:
    - containerPort: 22
      name: ssh
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
